### ISSUE TITLE
[Bug]: When placed during rainning some transparent textures are broken

### ISSUE THREAD

**Issue by DevDyna** [Mrbysco/RainShield#2]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.3.7

### Minecraft version

1.19.2

### Mod version

RainShield-1.19-1.1.1

### Java version

java 20.0.1

### Issue Description

when placed the rain shield , many textures like flowers , water and other blocks look like have a mirrored layer that break the texture

---
# as normal
![2024-02-27_12 36 15](https://github.com/Mrbysco/RainShield/assets/78147916/560efd5e-0327-486d-aab6-68ae1a941c37)

# during rainning
![2024-02-27_12 36 24](https://github.com/Mrbysco/RainShield/assets/78147916/a98215a1-c49b-4abf-8d2f-46a208bcda8b)

# after placed rain shield
![2024-02-27_12 36 29](https://github.com/Mrbysco/RainShield/assets/78147916/d7aeb399-2efd-4972-a6b7-841470b63e3a)

# without rainning -> probably caused by particles effect
![2024-02-27_12 45 10](https://github.com/Mrbysco/RainShield/assets/78147916/a8f7025a-2203-436f-86aa-9ce07661c7b3)

modpack used:
[IronBerry Expert 0.8b](https://legacy.curseforge.com/minecraft/modpacks/ironberry-expert) *where i have found and tested , idk if persist on previous*

**Comment by PoeticRainbow** [comment]
This issue also occurs on the FTB Skies modpack (1.19.2). When the Rain Shield is actively blocking the rain, all backfaces of blocks are rendered. You can see this even better with blocks like Glass and Leaves. Going into spectator and clipping in to the ground will also show the issue more clearly.

**Comment by Mrbysco** [comment]
Should be fixed with this commit https://github.com/Mrbysco/RainShield/commit/2d5337bf9a3fcb347fd37cb2279000051876c0c9 but I forgot to cause a new build to be uploaded

**Comment by Mrbysco** [comment]
A version is being built and uploaded
